name: Build Developer Docs

on:
  push:
    branches:
    - trunk

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.2.0
    - name: Set Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: composer install
      run: composer install --no-dev
    - name: npm install, build, and build hookdocs
      run: |
        npm install
        npm run build
        npm run build:docs
    - name: Deploy docs update
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './docs'
