name: Build Hook Docs

on:
  push:
    branches:
    - trunk

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Set Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: composer install
      run: composer install --no-dev
    - name: npm install, build, and build hookdocs
      run: |
        npm install
        npm run build
        npm run build:docs
    - name: Deploy docs update
      uses: maxheld83/ghpages@v0.3.0
      env:
        BUILD_DIR: 'docs/'
        GH_PAT: ${{ secrets.GH_PAT }}
